MajorDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('news_extraction.urls')),
    url(r'^visualize/', include('graph.urls')),
]

graph/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'graph'

urlpatterns = [
    url(r'^ktm-map/$', views.kathmandumap, name='kathmandu'),
    url(r'^location/$', views.bargraph, name='location'),
    url(r'^searchnumber/$', views.searchnumber, name='search'),
    url(r'^nepal-map/$', views.nepalmap, name='nepal'),
    url(r'^linegraph/$', views.linegraph, name='linegraph'),
]

news_extraction/urls.py
from django.conf.urls import url
from . import views

app_name = 'news_extraction'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'extraction$', views.extraction, name='extraction'),
    url(r'about_us', views.about_us, name='about_us'),
    url(r'contact_us', views.contact_us, name='contact_us'),
    url(r'search', views.searchquery, name='searchquery'),
]

news_extraction/models.py
from datetime import date

from django.db import models

class rssdata(models.Model):
    header = models.CharField(blank=True, max_length=200)
    body = models.TextField(blank=False, null=False)
    source = models.CharField(blank=True, max_length=200, null=True)
    death = models.CharField(blank=True, max_length=200, null=True)
    death_no = models.IntegerField(default=0,blank=True, null=True)
    injury = models.CharField(blank=True, max_length=200, null=True)
    injury_no = models.IntegerField(default=0,blank=True, null=True)
    location = models.CharField(blank=True, max_length=200, null=True)
    vehicleone= models.CharField(blank=True, max_length=200, null=True)
    vehicletwo = models.CharField(blank=True, max_length=200, null=True)
    date = models.CharField(default=date.today, blank=True, null=True,max_length=100)
    link = models.CharField(blank=True, max_length=200, null=True)
    vehicle_no = models.CharField(blank=True, max_length=200, null=True)
    vehicle_type = models.CharField(blank=True, max_length=200, null=True)
    month = models.CharField(blank=True, max_length=200, null=True)
    year = models.CharField(blank=True, max_length=200, null=True)
    day = models.CharField(blank=True, max_length=200, null=True)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'rssdata'
        ordering = ('-date', 'location','vehicleone','vehicletwo')

    def save(self, *args, **kwargs):
        super(rssdata, self).save(*args, **kwargs)

    def __str__(self):
        return self.header

news_extraction/forms.py
from django import forms


class NameForm(forms.Form):
    news_link = forms.CharField(max_length=500)

news_extraction/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from forms import NameForm
from .models import *
from methods import *
from django.db.models import Q

def index(request):
    initial_check()
    news_list = rssdata.objects.all().order_by("-date")
    page = request.GET.get('page', 1)

    paginator = Paginator(news_list, 5)
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'news': news})


def extraction(request):
    if request.method == 'POST':
        form = NameForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            extracted_data = data['news_link']
            link, news , title = manual_extract(extracted_data)

            #
            # If you want to save the input news
            oldlinks = rssdata.objects.values_list('link', flat=True)

            if link not in oldlinks:
                id = extract(link, news, title)
                return render(request, 'extraction.html', {'form': form,
                                                           'news_id': id,
                                                           'article': rssdata.objects.get(pk=id)})
            else:
                id = 5
                return render(request, 'extraction.html', {'form': form,
                                                           'news_id': id,
                                                           'article': rssdata.objects.get(link=link)})


        # #

            #

    else:
        form = NameForm()

    return render(request, 'extraction.html', {'form': form})


def about_us(request):
    return render(request, 'about_us.html')


def contact_us(request):
    return render(request, 'contact_us.html')

def searchquery(request):
    if request.POST:
        query = request.POST.get('query', None)
        querylist = rssdata.objects.values('body').filter(Q(body__icontains=query))

        return render(request, 'searchquery.html',{'searchquery':querylist,
                                                    'query':query,})

news_extraction/templates/about_us.html
{% extends "base.html" %}
{% block title %} News Information Extraciton {% endblock title %}

{% block nav_index_about_us %} class="nav-link active btn-primary" {% endblock nav_index_about_us%}

{% block content %}
<style>
    .row{
    margin-top:10px;
    margin-bottom: 10px;
    }
    .team{
    float: left;
    text-align: center;
    }
    .person{
    height: 200px;
    width: 200px;
    background-color: #555;
    border-radius: 50%;
    }
    .git{
    width: 30px;
    height: 30px;
    }
    .gmail{
    width: 30px;
    height: 30px;
    margin-left: 5%;
    }
</style>

<div class="container">
    <div class="col-lg-12 text-center">
      <h1> Our Team </h1>
    </div>
    <div class="row justify-content-md-center">
        <div class="team"><img class="person" src="../static/team/aman.jpg"/>
            <div class="intro"><h3>Dr. Aman Shakya</h3><small>Supervisor</small>
            </div>
        </div>
    </div><br><br>

    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 style="font-size:30px;margin:auto;"><strong>Developers</strong></h2>
        </div>
    </div><br>
    <div class="row justify-content-md-center">
        <div class="team col-sm-3"><img class="person" src="../static/team/basanta.jpg"/>
            <div class="intro"><h3>Basanta Chaulagain</h3><small>Backend Developer</small><br>
                <a href="https://github.com/BasantaChaulagain"><img class="git" src="../static/team/github.png"></a>
                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=071bct510@pcampus.edu.np">
                    <img class="gmail" src="../static/team/gmail.png"></a>
            </div>
        </div>

        <div class="team col-sm-3"><img class="person" src="../static/team/bhuwan.jpg"/>
            <div class="intro"><h3>Bhuwan Bhatt</h3><small>NLP, Data Processing</small><br>
                <a href="https://github.com/bhattbhuwan13"><img class="git" src="../static/team/github.png"></a>
                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=071bct511@pcampus.edu.np"><img class="gmail" src="../static/team/gmail.png"></a>
            </div>
        </div>

        <div class="team col-sm-3">
            <img class="person" src="../static/team/bishal.jpg"/>
            <div class="intro"><h3>Bishal Chaulagain</h3><small>Frontend Developer</small><br>
                <a href="#"><img class="git" src="../static/team/github.png"></a>
                <a href="#"><img class="gmail" src="../static/team/gmail.png"></a>
            </div>
        </div>

        <div class="team col-sm-3">
            <img class="person" src="../static/team/dip.JPG"/>
            <div class="intro"><h3>Dipkiran Pradhan</h3><small>Data Visualization, Backend Deveo</small><br>
                <a href="https://github.com/Dipkiran"><img class="git" src="../static/team/github.png"></a>
                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=071bct516dip@pcampus.edu.np">
                    <img class="gmail" src="../static/team/gmail.png"></a>
            </div>
        </div>
    </div><br>
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 style="font-size:25px;margin:auto;"><strong>Credits</strong></h2>
        </div>
    </div><br>
    <div class="row justify-content-md-center">
        <div class="team col-sm-3"><img class="person" src="../static/team/amit.jpg"/>
            <div class="intro"><h3> Amit Bhandari</h3><br>
            </div>
        </div>
        <div class="team col-sm-3"><img class="person" src="../static/team/basantadai.jpg"/>
            <div class="intro"><h3>Basanta Maharjan</h3><br>
            </div>
        </div>
        <div class="team col-sm-3"><img class="person" src="../static/team/kritish.jpg"/>
            <div class="intro"><h3>Kritish Pahi</h3><br>
            </div>
        </div>


    </div>
</div>
{% endblock content %}

news_extraction/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} NIEV {% endblock title %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google map
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  -->

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.4.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--{% block css %}-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'css/news.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css"/>

    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript" src="{% static 'js/graph/d3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/graph/topojson.v1.min.js' %}"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/districts.css' %}" media="screen" rel="stylesheet" type="text/css">

    <style>
    .page-header{
      background: url({% static "img/road.jpe" %} );
      background-size:100%;
      /*background-position: center;*/
      height:80px;
      width:100%;
      margin: 0.1px;
    }
    ul{
      list-style-type: none;
    }
    .navbar-nav li{
      /*color: #fff;*/
      display: inline;
      font-family: sans-serif;
      font-weight: 600;
      font-size: 12px;
      margin-right: 25px;
      text-transform: uppercase;
    }
    .navbar{
      background-color: black;
    }
    small{
    font-size: 16px;
    }
    .dropbtn {
    background-color: black;
    color: white;
    font-size: 16px;
    border: none;
    font-weight:600;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 0;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #000; color: #fff;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: black;}

    </style>

    {% endblock css %}

    <div class="jumbotron-fluid" style="background-color:#a2cf6e;">
        <div class="container header-container" style="font-family:helvetica">
            <h2 style="margin-left: 0;">Casualties Information Extraction, Analysis and Visualization</h2>
        </div>
    </div>

    <nav class="navbar navbar-toggleable-sm navbar-fixed-top">

        <div class="collapse navbar-collapse container-fluid" style="padding-left:5%; padding-right:5%">
            <div class="nav-left" style="margin:auto;">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a {% block nav_index_home %} {% endblock nav_index_home %} href="/" style="color:#618833;">Home</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_visualization %} {% endblock nav_index_visualization %} href = "{% url 'graph:location' %}" style="color:#618833;"> Visualization </a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_searchno %} {% endblock nav_index_searchno %} href = "{% url 'graph:search' %}" style="color:#618833;"> Search Vehicle </a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_kathmandu %} {% endblock nav_index_kathmandu %} href = "{% url 'graph:kathmandu' %}" style="color:#618833;"> Kathmandu Map </a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_nepal %} {% endblock nav_index_nepal %} href="{% url 'graph:nepal' %}" style="color:#618833;">Nepal Map</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_linegraph %} {% endblock nav_index_linegraph %} href="{% url 'graph:linegraph' %}" style="color:#618833;">Line Graph</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_extraction %} {% endblock nav_index_extraction %} href="/extraction" style="color:#618833;">Extraction</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_about_us %} {% endblock nav_index_about_us %} href="/about_us" style="color:#618833;">About Us</a></li>
                </li>

            </ul>
                </div>

            <div class="ml-auto" style="margin:auto;">
                <form class="form-inline" action="/search/" method="post">
                  {% csrf_token %}
                    <input class="form-control mr-sm-2" name="query" type="text" placeholder="Search"
                           required="required">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    </div>
    </div>
</head>

<body>
{% block content %}
{% endblock content %}
{% block javascript %}

{% endblock javascript %}

<!-- Footer -->
<!-- Just In Case -->
<br>
<br>
<br>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<div style="position:fixed;bottom:0;height:auto;margin-top:10%;width:100%;text-align:center;background-color: #D3D3D3;padding-top:10px;padding-bottom:10px;">
Copyright &copy; Road Accident Information Extraction and Analysis 2018
</div>

</body>
</html>

news_extraction/templates/base1.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- <meta http-equiv="x-ua-compatible" content="ie=edge"> -->
    <!-- <meta http-equiv="refresh" content="5; URL=http://127.0.0.1:8000/rssdb/" > -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %} NIEV {% endblock title %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google map
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  -->

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.4.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>

    <link rel="stylesheet" href="{% static 'css/news.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" type="text/css"/>

    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript" src="{% static 'js/graph/d3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/graph/topojson.v1.min.js' %}"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/districts.css' %}" media="screen" rel="stylesheet" type="text/css">

    <style>
    .page-header{
      background: url({% static "img/road.jpe" %} );
      background-size:100%;
      /*background-position: center;*/
      height:80px;
      width:100%;
      margin: 0.1px;
    }
    ul{
      list-style-type: none;
    }
    .navbar-nav li{
      /*color: #fff;*/
      display: inline;
      font-family: sans-serif;
      font-weight: 600;
      font-size: 12px;
      margin-right: 25px;
      text-transform: uppercase;
    }
    .navbar{
      background-color: black;
    }
    small{
    font-size: 16px;
    }
    .dropbtn {
    background-color: black;
    color: white;
    font-size: 16px;
    border: none;
    font-weight:600;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 0;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #000; color: #fff;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: black;}

    </style>

    {% endblock css %}

    <div class="jumbotron-fluid">
        <div class="container" style="font-family:helvetica">
            <h2>Road Accident Information Extraction and Analysis</h2>
            <small>A Database Collection of Road Accident in Nepal</small>
        </div>
    </div>

    <nav class="navbar navbar-toggleable-md ">
        <!-- <nav class="navbar navbar-default"> -->

        <div class="collapse navbar-collapse" style="padding-left:10%; padding-right:10%">
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a {% block nav_index_home %} {% endblock nav_index_home %} style="color:white;" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_visualization %} {% endblock nav_index_visualization %}href = "{% url 'graph:location' %}" style="color:white;"> Visualization </a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_searchno %} {% endblock nav_index_searchno %}href = "{% url 'graph:search' %}" style="color:white;"> Search vehicleNo. </a>
                </li>

                <li class="nav-item">
                    <a {% block nav_index_database %} {% endblock nav_index_database %} style="color:white;" href="#">Database</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_extraction %} {% endblock nav_index_extraction %} style="color:white;"
                       href="/extraction">Extraction</a>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_about_us %} {% endblock nav_index_about_us %} style="color:white;" href="/about_us">About
                        Us</a></li>
                </li>
                <li class="nav-item">
                    <a {% block nav_index_contact_us %} {% endblock nav_index_contact_us %} style="color:white;"
                       href="/contact_us">Contact Us</a></li>
                </li>
            </ul>

            <div class="ml-auto">
                <form class="form-inline" action="/search/" method="post">
                    <input class="form-control mr-sm-2" name="query" type="text" placeholder="Search"
                           required="required">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <!--
          <nav class="navbar navbar-inverse bg-inverse">
            <ul class="navbar-nav">
              <li {% block nav_indexy %} {% endblock nav_indexy %}><a style="color:white;" href="/news/" >Home</a></li>
              <li {% block nav_indexy_e %} {% endblock nav_indexy_e %} ><a style="color:white;" href="/news_ie/" >Extraction</a></li>
              <li><a style="color:white;"  href="#">About Us</a></li>
            </ul>
        </nav>
      -->
    <br>
    </div>
    </div>
</head>

<body>
{% block content %}
{% endblock content %}
{% block javascript %}

{% endblock javascript %}

<!-- Footer -->
<!-- Just In Case -->
<br>
<br>
<br>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<!--<div style="position:fixed;bottom:0;height:auto;margin-top:40px;width:100%;text-align:center;background-color: #D3D3D3;padding-top:10px;padding-bottom:10px;">-->
<!--Copyright &copy; Road Accident Information Extraction and Analysis 2018-->
<!--</div>-->

</body>
</html>

news_extraction/templates/extraction.html
{% extends "base.html" %}
{% block title %} News Information Extraciton {% endblock title %}

{% block nav_index_extraction %} class="nav-link active btn-primary" {% endblock nav_index_extraction%}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
        <form action="/extraction" method="post">
        {% csrf_token %}
        {{ form }}
            <input  class="btn btn-info" type="submit" value="Submit"/>
        </form>
    </div>

      <div class="col-md-6">
      <p id='summary'> Please enter the news title and news body.</p>
      </div>
    </div>
</div>

{% endblock content %}


{% block javascript %}
<style>
.listed{
  background-color: rgb(169, 210, 237);
  color:#000;
  padding: 5px;
  border-radius: 15px;
  margin: 5px;
}
div.center {text-align: center;}
.pre-scrollable {
    max-height: 700px;
    overflow-y: scroll;
}
</style>

<script>
$(document).ready(function(){
console.log("hello");
  function present_summary(){
    var accidentNews ={};
    accidentNews[{{news_id}}] = {
        location : "{{ article.location }}",
        death : "{{ article.death }}",
        death_no : "{{ article.death_no }}",
        injury:"{{ article.injury}}",
        injury_no:"{{ article.injury_no}}",
        vehicleone:"{{ article.vehicleone }}",
        vehicletwo:"{{ article.vehicletwo }}",
        vehicle_no:"{{ article.vehicle_no }}",
        date:"{{ article.date }}",
        day:"{{ article.day }}",
        body:"{{article.body}}",
    };

    var news = accidentNews[{{news_id}}];
    $('#summary').replaceWith("<div id='summary'><h2> Extracted items </h2> <p><strong> Death: </strong>" + news.death +  "</p>        <p><strong> Death Number: </strong>" + news.death_no +  "</p>        <p><strong> Injury: </strong>" + news.injury +"</p>        <p><strong> Injury Number: </strong>" + news.injury_no +"</p>        <p><strong> Vehicle Involved: </strong>" + news.vehicleone +"</p>    <p><strong> Vehicle Involved: </strong>" + news.vehicletwo +"</p>      <p><strong> Vehicle Numbers: </strong>" + news.vehicle_no +"</p>        <p><strong>Location: </strong>" + news.location +"</p>        <p><strong> Date: </strong>"+ news.date +"</p>        <p><strong> Day: </strong>"+ news.day +"</p>        <h4>Full news</h4>"+ news.body+ "</div>");
  $('#no').click(function () {
    $('#summary').replaceWith("<h2 id='summary'> No Summary Information</h2>");
  })
  }
  present_summary();
});
</script>

{% endblock javascript %}

news_extraction/templates/index.html
{% extends "base.html" %}
{% block title %} News Information Extraciton {% endblock title %}

{% block nav_index_home %} class="nav-link active btn-primary" {% endblock nav_index_home%}

{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-6">
        <div class="pre-scrollable">
        {% for article in news %}
          <ul>
            <li class='listed' style='list-style:none;'>
              <p id={{ article.id }} class="head"> <a href="#" style="color:#4b0082">{{article.header}}:</a><br>
              <a>{{article.date}}</a>

            </p>
            </li>
          </ul>
        {% endfor %}
        </div>

        <div class="pagination-div" style="margin-top:20px;">
        {% if news.has_other_pages %}
        <ul class="pagination">
            {% if news.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ news.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in page_range %}
              {% if news.number == i %}
            <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only ">(current)</span></span></li>
              {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if news.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ news.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
        </div>
    </div>

    <div class="col-md-6">
      <p id='summary'> Click on one of the news </p>
    </div>
    </div>
</div>
{% endblock content %}


{% block javascript %}
<style>
.listed{
  background-color: #a2cf6e;
  color:#000;
  padding: 20px;
  border-radius: 15px;
  margin: 5px;
  float: left;
  width: 90%;
}

div.center {text-align: center;}

.pre-scrollable {
    max-height: 450px;
    overflow-y: scroll;
}
.source{

float:left;
font-size:12px;
}
.source p{
border: 2px solid black;
border-radius:20px;
padding : 3% 3%;
}
</style>

<script>
$(document).ready(function(){
console.log("hello");
  function present_summary(){
    var accidentNews ={};
    {% for article in news %}
    {% if article.id != None %}
    accidentNews[{{article.id}}] = {
        location : "{{ article.location }}",
        death : "{{ article.death }}",
        death_no : "{{ article.death_no }}",
        injury:"{{ article.injury}}",
        injury_no:"{{ article.injury_no}}",
        vehicleone:"{{ article.vehicleone }}",
        vehicletwo:"{{ article.vehicletwo }}",
        vehicle_no:"{{ article.vehicle_no }}",
        vehicle_type:"{{ article.vehicle_type }}",
        date:"{{ article.date }}",
        day:"{{ article.day }}",
        body:"{{article.body}}",
    };
    {% else %}

    accidentNews[0] = {};
    {% endif %}
    {% endfor %}

    $('.head').each(function(){
      $(this).click(function(){
        var news = accidentNews[this.id];
        $('#summary').replaceWith("<div id='summary'><h2> Extracted items </h2> <p><strong> Death: </strong>" + news.death +  "</p>        <p><strong> Death Number: </strong>" + news.death_no +  "</p>        <p><strong> Injury: </strong>" + news.injury +"</p>        <p><strong> Injury Number: </strong>" + news.injury_no +"</p>        <p><strong> Vehicles: </strong>" + news.vehicleone + ", " + news.vehicletwo +"</p> <p><strong> Vehicle Numbers: </strong>" + news.vehicle_no +"</p>    <p><strong> Vehicle Type: </strong>" + news.vehicle_type +"</p>    <p><strong>Location: </strong>" + news.location +"</p>      <p><strong> Date: </strong>"+ news.date +"</p>        <p><strong> Day: </strong>"+ news.day +"</p>        <h4>Full news</h4>"+ news.body+ "</div>");
  }); 

  $('#no').click(function () {
    $('#summary').replaceWith("<h2 id='summary'> No Summary Information</h2>");
  })
    });
  }
  present_summary();
});

</script>

{% endblock javascript %}

news_extraction/templates/searchquery.html
{% extends "base.html" %}
{% block title %} News Information Extraciton {% endblock title %}

{% block nav_index_about_us %} class="nav-link active btn-primary" {% endblock nav_index_about_us%}

{% block content %}
<h1 style=" margin-top:2%; margin-left: 5%; margin-right: 5%;"> Result for : {{query}}</h1>
{% for search in searchquery %}
<p style="font-size:14px; margin-top:2%; margin-left: 5%; margin-right: 5%;">{{ search.body }}</p><br>
{% endfor %}
{% endblock content %}